require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'
# use_frameworks!

target 'tflite' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'TensorFlowLite', '1.12.0'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera/Permission-Camera.podspec"

  # target 'tfliteTests' do
  #   inherit! :complete
  #   # Pods for testing
  #   pod 'RNFS', :path => '../node_modules/react-native-fs'
  #   pod 'TensorFlowLite', '1.12.0'
    
  #   

  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'tflite-tvOS' do
  # Pods for tflite-tvOS

  target 'tflite-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
